### ISSUE TITLE
I can't install using XCode Package or CocoPods

### ISSUE THREAD

**Issue by h-elbeheiry** [exyte/ScalingHeaderScrollView#10]
Says no compatible version found, there is no ver 1.0.0 in xcode package manager, and cocopods throw this error even without specifying a version:  CocoaPods could not find compatible versions for pod "ScalingHeaderScrollView":
  In Podfile:
    ScalingHeaderScrollView

**Comment by jamajk** [comment]
You need to specify version '0.0.3' as this seems to be the newest release.
Nevertheless readme should be updated

**Comment by f3dm76** [comment]
Hey @h-elbeheiry, for SPM usually you don't need to specify a certain version, better use "up to next major", looks like this - automatically inserting the correct version
<img width="842" alt="Screenshot 2022-09-15 at 13 43 07" src="https://user-images.githubusercontent.com/9447630/190323661-78466323-7b8b-462a-9a73-c5cf799b2cd0.png">
Anyway I removed hard set version for readme, sorry about that. 

About Cocoapods, could you please attach your pod file? Here is mine and it works as expected:
```
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def pods
  pod 'ScalingHeaderScrollView'
end
 
target 'asd' do
    pods
end
```
