### ISSUE TITLE
When used, I get a message in the console onChange(of: CGRect) action tried to update multiple times per frame.

### ISSUE THREAD

**Issue by Foreman76** [exyte/ScalingHeaderScrollView#11]
This simple code

https://gist.github.com/Foreman76/a07531c1e76c8880a9780fcb87d8ebf7

if not use animation or NavigationLink  everything is good

what am I doing wrong. Any ideas

**Comment by f3dm76** [comment]
Hey @Foreman76, I launch your project it seems to work ok both with navigation view and without. Maybe I'm missing something, could you please make a video and describe what you would like instead?

**Comment by f3dm76** [comment]
Beg your pardon @Foreman76, I just needed to tap on of the rows. Fixed in version 0.0.6, please do check it out, have a great day!

**Comment by Foreman76** [comment]
Thanks
