### ISSUE TITLE
Different iOS Deployment target between Cocoapods & SPM

### ISSUE THREAD

**Issue by puzzlemoondev** [exyte/ScalingHeaderScrollView#12]
Is there a reason why the pod's minimum deployment target is set to iOS 14 while swift package's set to iOS 15?
We use spm and target iOS 14 but are forced to use cocoapods.

**Comment by f3dm76** [comment]
Hey @puzzlemoondev, lowered the target, have a nice day

**Comment by puzzlemoondev** [comment]
thank you!
