### ISSUE TITLE
Odd offset when displayed as a modal

### ISSUE THREAD

**Issue by dwnz** [exyte/ScalingHeaderScrollView#17]
Not sure if this is a bug or a known tradeoff, but is there a way to adjust the offset of the header when the screen is being displayed as a popup? Wanting to allow users to drag the screen down. Have tried a few different things but can't quite crack it

![IMG_2597](https://user-images.githubusercontent.com/295392/220067044-402428fb-4dae-4452-97db-27e3b414a0f5.jpeg)

**Comment by f3dm76** [comment]
Hey @dwnz, sorry for the late answer, but I'm happy to let you know I added an adjustment for cases like yours, please give version 0.1.1 a go. Have a marvellous day!

**Comment by dwnz** [comment]
@f3dm76 Amazing, works perfectly - that has made my day. Thanks heaps for the fix (and the epic plugin)
