### ISSUE TITLE
error: The package product 'Introspect' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13 (in target 'ScalingHeaderScrollView' from project 'ScalingHeaderScrollView')

### ISSUE THREAD

**Issue by webserveis** [exyte/ScalingHeaderScrollView#26]
When select My Mac, and build failed

How to fix this?

`error: The package product 'Introspect' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13 (in target 'ScalingHeaderScrollView' from project 'ScalingHeaderScrollView')`

**Comment by f3dm76** [comment]
Hey @webserveis, sorry this package is not supposed to support macOs in the first place. All fixed now, thanks for bringing this to our attention. Have a great day!
