### ISSUE TITLE
CPU usage 102%

### ISSUE THREAD

**Issue by osxsystem** [exyte/ScalingHeaderScrollView#28]
Tools: Xcode Version 14.3.1, iPhone 14 Pro Simulator(iOS 16.4)
- reproduce:
Run the example app, navigate to the "Banking Screen"
- Debug Log:

```
ForEach<Array<BankTransaction>, UUID, TransactionView>: the ID 49BB3E99-EF2E-4939-9097-361C36DE5B36 occurs multiple times within the collection, this will give undefined results!
```

![Screenshot 2023-07-31 at 3 53 43 PM](https://github.com/exyte/ScalingHeaderScrollView/assets/27819473/636b5118-c5b7-485a-a55e-78ffabe4919c)

**Comment by f3dm76** [comment]
Hey @osxsystem, are you using ScalingHeader version 0.2.0? Since there was a fix for perfomance recently, and I want to make sure this fix didn't help with your problem. Have a nice day
