### ISSUE TITLE
introspectTableView deprecated

### ISSUE THREAD

**Issue by muhasturk** [exyte/ScalingHeaderScrollView#36]
'introspectTableView(customize:)' is deprecated: The Introspect module is deprecated and will be obsoleted later this year. Please switch over to the new and improved SwiftUIIntrospect module. More info: https://github.com/siteline/swiftui-introspect#readme

**Comment by f3dm76** [comment]
Hey @muhasturk, please check out version 1.0.3, have a wonderful day!
