### ISSUE TITLE
Doesn't work on iOS 17

### ISSUE THREAD

**Issue by DEV1ANT7** [exyte/ScalingHeaderScrollView#40]
Hello, the whole library doesn't work properly in iOS 17. I've tried more complex views and even sample code, collapse progress doesn't work at all.

Same code on [iOS 16](https://imgur.com/a/CY4FD0Q) and then [iOS 17](https://imgur.com/a/96vgOMC). 
iOS 16 was on the simulator, iOS 17 I tried both the simulator and the real device

**Comment by f3dm76** [comment]
Hey @muhasturk, please check out version 1.0.3, the issue should be fixed there, have a nice day
