### ISSUE TITLE
Bug: Unresponsive Tap Area in Shrunk Header

### ISSUE THREAD

**Issue by BelobogEth** [exyte/ScalingHeaderScrollView#41]
I have encountered a bug in the "Scaling Header Scroll View". When the header is in its shrunk state, there is an unresponsive tap area in the region where the header would be expanded. 
Please see attached video.

This issue can be temporarily resolved by disabling allowsHitTesting on the header, but this also allows interactions with buttons even when they are under the collapsed header, which is not the desired behavior.

Environment:
iOS version: 17.0.3
Xcode version: 15.0.1

https://github.com/exyte/ScalingHeaderScrollView/assets/148549940/df884465-0c87-4855-8c91-26cf5aba1549

**Comment by f3dm76** [comment]
Hey @BelobogEth, thank you so much for bringing this to our attention. Please check out version 1.0.4, have a wonderful day!

**Comment by BelobogEth** [comment]
Works fine, thanks!
