### ISSUE TITLE
Is there "detect scrollview has reach bottom" capability?

### ISSUE THREAD

**Issue by ivanpnn** [exyte/ScalingHeaderScrollView#42]
Hi, firstly thank you for the great and helpful package.
I've worked a little time with the package.
In my use case, I need to detect whether the scroll view scrolled has reached bottom or not.
Is there is any function or work around to get the capability "detect scrollview has reach bottom"?

Thank you in advance. Have a great day.

**Comment by f3dm76** [comment]
Hey @ivanpnn, please check out version 1.1.0, where didReachBottom has been added. Have a great day!
