### ISSUE TITLE
Using tabview inside content block

### ISSUE THREAD

**Issue by Sharrykhan01** [exyte/ScalingHeaderScrollView#43]
Hi 
I am using tabiew with three views inside the ScallingHeaderScrollview content block, there is a height issue for the TabView views. The data is getting cut. Can't we provide dynamic height for the Tabview so that the complete data get scrolled and be visible.

**Comment by f3dm76** [comment]
Hey @Sharrykhan01, you'll have to fix your table's height from your end - there is no way for me to get the height for your table from the ViewBuilder the library gets. There is an example of such a behaviour in the example project - search for 'AutosizingList'

**Comment by Sharrykhan01** [comment]
This is the code if you find something, please let me know.                     
                                ScalingHeaderScrollView {
                                    ZStack {
                                        Color.white.opacity(1.0)
                                        self.setTopHeader(size: geo.size)
                                    }
                                } content: {
                                    TabView(selection: $tabIndexSelected) {
                                        VStack(spacing: 0) {
                                            LOCBussinesProfileAbout(size: geo.size,
                                                                    businessResult: [data],
                                                                    height: $pageHeights[0],
                                                                    shouldScroll: $shouldScroll,
                                                                    showOpeningHours  : $showOperatingHours,
                                                                    isEventEdited : $isEventEdited,
                                                                    askForSignIn : $askForSignIn,
                                                                    detailListObj : self.detailListObj, isforUserProfile : isforUserProfile)
                                            .frame(height: pageHeights[tabIndexSelected] > geo.size.height - 170 ? nil :  (geo.size.height - 170),alignment : .top)
                                        }
                                        .tag(0)
                                        
                                        VStack(spacing: 0) {
                                            self.commentsTabView(size: geo.size)
                                            Spacer()
                                        }
                                        .frame(height: pageHeights[tabIndexSelected] > geo.size.height - 220 ? nil :  (geo.size.height - 220),alignment : .top)
                                        .tag(1)
                                        VStack(spacing: 0) {
                                            LOCBusinessMedia(businessId: self.businessID,
                                                             height: $pageHeights[2],
                                                             shouldScroll: $shouldScroll,
                                                             isShowBackBtn: isShowBackBtn ?? false,
                                                             askForSignIn: $askForSignIn,
                                                             loadMorePhotos: $loadMorePhotos,
                                                             size: geo.size,
                                                             progress: self.progress,
                                                             isFromBusinessProfile: true,
                                                             businessName : data.businessName ?? "",
                                                             businessImage : data.imageIDS?.first?.file ?? "")
                                            .padding(.bottom, 0)
                                            Spacer()
                                        }
                                        .frame(height: pageHeights[tabIndexSelected] > geo.size.height - 170 ? nil :  (geo.size.height - 170),alignment : .top)
                                        .tag(2)
                                    }
                                    .tabViewStyle(PageTabViewStyle())
                                    .frame(height: pageHeights[tabIndexSelected])
                                    .animation(.none)
                                    .transition(.slide)
                                    .background(Color.listBackground)
                                }
                                .collapseProgress($progress)
                                .height(min: 150, max: self.headerHeight)
                                .allowsHeaderGrowth()

**Comment by f3dm76** [comment]
@Sharrykhan01 Oh, TabView - not TableView, I do apologize. Does it work in a regular ScrollView?

**Comment by Sharrykhan01** [comment]
@f3dm76  Got it man! sounds cool, it is for certain devices to which tabview showing irregular behaviour. But fine ihave to search for other pager view. If you find better please have a ping for me.
Thanks bro!

**Comment by MDXDave** [comment]
I ran into the same issue, however i fixed it with this solution:
https://bdewey.com/til/2023/03/01/swiftui-and-tabview-height/
