### ISSUE TITLE
Header doesn't respect MaxHeight in sub-view

### ISSUE THREAD

**Issue by ioslife** [exyte/ScalingHeaderScrollView#45]
When using the ScalingHeader in a view inside of a NavigationStack, the user can start to swipe up and then quickly swipe down to cause white space to show up. 
https://github.com/exyte/ScalingHeaderScrollView/assets/5478660/de92ae7e-d827-48ab-b0a9-fb837280ce52

**Comment by ioslife** [comment]
There might be a configuration property I need to change, but I don't see any documentation around it

**Comment by f3dm76** [comment]
Hey @ioslife, do you mean this white space?
<img width="326" alt="Screenshot 2023-12-13 at 12 14 19" src="https://github.com/exyte/ScalingHeaderScrollView/assets/9447630/a6e3f587-a151-442b-939a-97c96512707f">

**Comment by ioslife** [comment]
@f3dm76, no, not that white space. I am talking about the white space that can be created in the status bar
![IMG_80B68E9EAC2B-1](https://github.com/exyte/ScalingHeaderScrollView/assets/5478660/71a18e68-5e29-48ea-80dc-794b680fef44)

**Comment by f3dm76** [comment]
@ioslife did you try headerAlignment modifier?

**Comment by ioslife** [comment]
> @ioslife did you try headerAlignment modifier?

Just tried it, no dice

When the page is on the root of the navStack, it works as expected. It also looks like I want it to when the page initially loads. 

It's just when scrolling that this happens like in the video I posted.

**Comment by ioslife** [comment]
@f3dm76 I just solved my issue. The problem occurs when the view does not have `.navigationBarTitleDisplayMode(.inline)` set.

**Comment by ioslife** [comment]
I would still say this is an issue. IMO you shouldn’t have to set the navStyle

**Comment by f3dm76** [comment]
In this case, please provide full minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day
