### ISSUE TITLE
Header Image & Modal Sheet

### ISSUE THREAD

**Issue by thomaskioko** [exyte/ScalingHeaderScrollView#46]
Hey folks, I tried out the library in my demo project but hit a small bump. In the content section, I added a list of items. The header has a weird behavior when I add a modal sheet. :(  This is also reproducible in the ProfileScreen example. I replaced the ContentView body with `ProfileScreen()` to display a `sheet` when clicking the hire button. Note: The longer the list, the lower the image.

Would you happen to know how to fix this?

https://github.com/exyte/ScalingHeaderScrollView/assets/841885/305fea0e-a145-44e3-bb4b-ce7809d7ea80

**Comment by f3dm76** [comment]
Hey @thomaskioko, thank you for bringing this to our attention. Please check out version 1.1.1 - should be fixed there. Have a wonderful day!
