### ISSUE TITLE
Scale header when scrolling up

### ISSUE THREAD

**Issue by ltns35** [exyte/ScalingHeaderScrollView#47]
Hi!

Could it be possible to display the header with max height when scrolling up at any point of the scrollview.

For example, filters on the headers that are hidden when scrolling down, but are shown when the user scrolls up a little bit.

**Comment by f3dm76** [comment]
Hey @ltns35, you can try using same min and max height. But it sounds like you really don't need this library, just use introspect to detect scroll offset

**Comment by Sharrykhan01** [comment]
@ltns35 Bro you can go for scrolling progress and handle out your header as per the preogress.
