### ISSUE TITLE
List Support as Content

### ISSUE THREAD

**Issue by muhasturk** [exyte/ScalingHeaderScrollView#50]
Currently list view as content is not supported. Do you have the plan to support it?

**Comment by f3dm76** [comment]
Hey @muhasturk, please remember that ScalingHeaderScrollView is just a ScrollView under the hood, so what you are asking is like asking to use a UITableView inside a UIScrollView. What you put inside a ScalingHeaderScrollView is entirely up to you, it just cannot have a scroll of its own. If you forbid your list to scroll, you can use it. There is an example of this in the Example project. You can also fork and try to just replace a 'ScrollView' with a 'List' if that's what you mean, have a nice day

**Comment by lyzkov** [comment]
We cannot use swipe actions without list support. :(
