### ISSUE TITLE
Scroll position gets reset after selecting new option for tab

### ISSUE THREAD

**Issue by lieancatch** [exyte/ScalingHeaderScrollView#55]
We have two tabs inside the scrollview. I scroll down inside the first tab and tap the second tab. Scrollview would scroll to top instead of retaining the current scroll position.

**Comment by f3dm76** [comment]
Hey @lieancatch, what if you replace ScalingHeaderScrollView with a regular ScrollView? If that works as expected, please attach a minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day
