### ISSUE TITLE
Broken on iOS 18 Beta 1

### ISSUE THREAD

**Issue by ioslife** [exyte/ScalingHeaderScrollView#57]

**Comment by parkwolfapp** [comment]
Seeing the same issue, my guess is we need to add .v18 to the introspect list

```
.introspect(.scrollView, on: .iOS(.v15, .v16, .v17)) { scrollView in
                configure(scrollView: scrollView)
            }
```

**Comment by f3dm76** [comment]
Thank you so much guys, @ioslife and @parkwolfapp! Please check out version 1.1.4, have a wonderful day!
