### ISSUE TITLE
Confused about FrameGetter

### ISSUE THREAD

**Issue by ioslife** [exyte/ScalingHeaderScrollView#59]
Hi there,

I am trying to understand how FrameGetter works for setting maxHeight dynamically, but I am failing to understand what to pass into frameGetter. Could you assist?

**Comment by f3dm76** [comment]
Hey @ioslife, sorry, but this is a generic SwiftUI question, and it's not about this library. Please refer to SO for help https://stackoverflow.com/questions/57577462/get-width-of-a-view-using-in-swiftui
