### ISSUE TITLE
Issues when presented as .pageSheet

### ISSUE THREAD

**Issue by adamdahan** [exyte/ScalingHeaderScrollView#6]
Hi all, 

Neat library, thanks for building it. I found some issues with the implementation. If you have a UIKit based app and want to present one of the examples inside of a nav with a modelPresentationStyle of .pageSheet with code like this: 

```
 @objc func presentOnboarding() {
        let onboardingViewController = UIHostingController(rootView: OnboardingView())
        let nav = UINavigationController(rootViewController: onboardingViewController)
        nav.modalPresentationStyle = .pageSheet

        if let sheet = nav.sheetPresentationController {
            sheet.detents = [.medium(), .large()]
        }
        present(nav, animated: true, completion: nil)
    }
 ```

You get this result (this is based off your `ColorScalingHeader` example). 
![Simulator Screen Recording - iPhone 13 - 2022-06-08 at 10 19 46](https://user-images.githubusercontent.com/1205894/172640628-a69e7cb5-de15-4610-8884-9f7239a2f5cd.gif)

Let me know if I can help further.

**Comment by f3dm76** [comment]
Hey @adamdahan, could you please share a code of how you create this image? If you are using Nuke it might be because of that...
